name: Simple CI - Manual Trigger

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to test with'
        required: false
        default: '3.13'
        type: choice
        options:
        - '3.13'
        - '3.12'
        - '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ github.event.inputs.python-version || '3.13' }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install Python dependencies
      run: |
        uv pip install --system --upgrade pip
        uv pip install --system -r requirements.txt
        uv pip install --system -r requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
    
    - name: Run tests with pytest
      run: |
        pytest tests/ -v
